### PR TITLE
Training typo

### PR DESCRIPTION
**Pull request by denis-yuen**
A couple typos

### CODE REVIEW

**Comment by tnabtaf** [comment]
Thanks @denis-yuen

**Comment by nsoranzo** [comment]
I don't see the changes on https://bcc2020.github.io/training/ , I suppose because these merged on the `training-nom` branch instead of `master`.

Also, there is another instance of `Prerquisites` in the same file.

**Comment by tnabtaf** [comment]
@nsoranzo Thanks.  Check now?  And working on the typo.

**Comment by nsoranzo** [comment]
Perfect, thanks!

**Pull request merged**
